name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore ImpactCalculator.sln
    - name: Build
      run: dotnet build ImpactCalculator.sln --configuration Release --no-restore 
    - name: Test Service
      run: dotnet test --no-restore --collect:"XPlat Code Coverage"
      working-directory: ImpactCalculator.CalculatorService/UnitTests
    - name: Test Client
      run: dotnet test --no-restore --collect:"XPlat Code Coverage"
      working-directory: ImpactCalculator.WebClient/UnitTests
